### ISSUE TITLE
crash when no free space is left on the file system(iOS 8.1.3)

### ISSUE THREAD

**Issue by panyult** [vitoziv/VIMediaCache#10]
```
- (void)setContentInfo:(VIContentInfo *)contentInfo {
    self.internalCacheConfiguration.contentInfo = contentInfo;
    
    [self.writeFileHandle truncateFileAtOffset:contentInfo.contentLength];
    [self.writeFileHandle synchronizeFile];
}
```
these codes lead to crashes,when when no free space is left on the file system(iOS 8.1.3)
Could you please add "@try{}@catch{}" or judgement before handle files,like "truncateFileAtOffset:",and same to other codes in the project.
thanks.

**Comment by vitoziv** [comment]
Check out  472d36f3cb
