### ISSUE TITLE
更换播放源时会卡住

### ISSUE THREAD

**Issue by DaokunBai** [vitoziv/VIMediaCache#13]
同一播放器，当更换播放源调用replaceCurrentItem时，会卡住
resourceLoaderManager = VIResourceLoaderManager()
playerItem = resourceLoaderManager?.playerItem(with: url)
player?.replaceCurrentItem(with: playerItem)

因为不想重复创建 AVPlayer，所以使用的replaceCurrentItem。
xcode 8.3
swift 3.1
模拟器 iPhone7

**Comment by vitoziv** [comment]
能提供一下 demo 么，我这边试了一下没有问题。

**Comment by smallqiang** [comment]
之前已经有许多人说过用replaceCurrentItem会比较卡，所以都是直接重新创建player会比较好的。

**Comment by vitoziv** [comment]
如果只是简单的 replaceCurrentItem ，上一个 item 的下载是不会停止的，如果希望停止下载，需要手动调用 VIResourceLoaderManager 的 cancelLoaders 方法
