### ISSUE TITLE
解析地址出错导致crash

### ISSUE THREAD

**Issue by crespoxiao** [vitoziv/VIMediaCache#20]
- (BOOL)resourceLoader:(AVAssetResourceLoader *)resourceLoader shouldWaitForLoadingOfRequestedResource:(AVAssetResourceLoadingRequest *)loadingRequest

这个delegate 实现里面 拿到的 originURL 是 nil ，导致播放的时候 crash 

试试这个地址：@"http://lavaweb-10015286.video.myqcloud.com/%E5%B0%BD%E6%83%85LAVA.mp4"。

**Comment by vitoziv** [comment]
已修复 ff8463fa6f

**Comment by crespoxiao** [comment]
@vitoziv    你贴的链接与当前问题并无关联

**Comment by vitoziv** [comment]
贴错了，是这个： 116124e23ac228a220e456ced5382260076a9156

**Comment by crespoxiao** [comment]
@vitoziv   多谢
再问一个问题，- (IBAction)toggleAction:(id)sender 执行后模拟器卡死，是什么原因呢

**Comment by vitoziv** [comment]
上面的问题，应该是看卡死在哪里了 🦀
