### ISSUE TITLE
i OS11系统下面不能播放视频

### ISSUE THREAD

**Issue by ilumanxi** [vitoziv/VIMediaCache#27]
Demo 中视频链接不能播放

**Comment by jgj1991** [comment]
demo中第三个url就不能播放，我的项目中很多也不能播放，我想知道下原因，请楼主解答啊

**Comment by jgj1991** [comment]
你是不是设置了判断视频多大的情况下才可以下载啊

**Comment by vitoziv** [comment]
不能播放的视频地址可以发出来么？

不能播放，有看到什么报错么？

**Comment by passol1988** [comment]
@vitoziv 
http://tu-img-1.aixinxi.net/o_1bvcmtnkkjsrn9aeg8vbajcva.mp4

**Comment by vitoziv** [comment]
用这个 commit 21926ff 试试，看还有没有问题。
