### ISSUE TITLE
how can i know cache finished easily?

### ISSUE THREAD

**Issue by mxyolande** [vitoziv/VIMediaCache#3]

**Comment by vitoziv** [comment]
Currently on develop branch, in [VICacheManager.h](https://github.com/vitoziv/VIMediaCache/blob/develop/VIMediaCache/URLProtocol/VICacheManager.h)

use `+ (VICacheConfiguration *)cacheConfigurationForURL:(NSURL *)url;` to get cache information.

```
VICacheConfiguration *configuration = [VICacheManager cacheConfigurationForURL:<URL>];
if (configuration.progress >= 1.0) {
    // cache done
}
```
