### ISSUE TITLE
您好 m4a 格式的音频是不支持的吗？

### ISSUE THREAD

**Issue by Mononster** [vitoziv/VIMediaCache#34]
cache m4a file是不work的 然后也不能播放~
谢谢回复！

**Comment by vitoziv** [comment]
能提供一下url 地址吗

**Comment by Mononster** [comment]
https://r18---sn-p5qlsney.googlevideo.com/videoplayback?id=efd892448b7f0b38&itag=139&source=youtube&requiressl=yes&mv=u&ms=au&ei=khDmWc-_CsGZ8gSZnLqAAQ&pl=20&mn=sn-p5qlsney&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1274427&lmt=1507343034858343&dur=214.180&mt=1508249164&key=dg_yt0&signature=256E79C739A75B4EB50F13C358AD0BB2412B256B.2C206C489FCD6BA96D8489F5513131C53B466958&ip=54.162.244.216&ipbits=0&expire=1508271346&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,ei,pl,mn,mm,ratebypass,mime,gir,clen,lmt,dur


https://r4---sn-5aanugx5h-tuvl.googlevideo.com/videoplayback?id=1d464e2af61cc7fa&itag=139&source=youtube&requiressl=yes&pl=16&pcm2cms=yes&initcwndbps=1427500&mn=sn-5aanugx5h-tuvl&mm=31&ms=au&ei=XSDmWcn4LsLWDJ6HtZAG&mv=m&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1122735&lmt=1507174495703027&dur=188.638&key=dg_yt0&signature=46409AFCA1BF81418A0A52240DE493F2B869935D.0751614359D1E496E2D476E795CAA78BDA7098B1&mt=1508253701&ip=129.97.124.14&ipbits=0&expire=1508275389&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,pcm2cms,initcwndbps,mn,mm,ms,ei,mv,ratebypass,mime,gir,clen,lmt,dur

这两个都是m4a

**Comment by vitoziv** [comment]
两个地址都失效了？

**Comment by vitoziv** [comment]
问题应该是和这个一样 https://github.com/vitoziv/VIMediaCache/issues/38

没有更多反馈的话，先关闭这个 issue 了
