### ISSUE TITLE
Cache file name conflict

### ISSUE THREAD

**Issue by KelaKing** [vitoziv/VIMediaCache#36]
`+ cachedFilePathForURL: `return url lastPathComponent
Example: _http://balabal1/temp.mp4_ and _http://balabal2/temp.mp4_ are different url, but saved as same file _temp.mp4_. Why not use md5 value of url as file name?

**Comment by vitoziv** [comment]
You are right, use md5 value will better, I change the file name to md5 value in this commit. cc: https://github.com/vitoziv/VIMediaCache/commit/1726e01f5dc412b9fb6fccb58a84d1013e851f86
