### ISSUE TITLE
带参url解析错误

### ISSUE THREAD

**Issue by EnderTan** [vitoziv/VIMediaCache#38]
如：http://f.us.sinaimg.cn:80/002Yzi6Slx07g1T7XBC801040100G8fF0k01.mp4?label=mp4_hd&template=25
视频url参数中有比MCurl首字母M大的参数，如上面的Template，就会解析出错误的originURL。

**Comment by vitoziv** [comment]
已修复，可以用最新 commit 的代码试试
cc: b927b03
