### ISSUE TITLE
change local file to cache

### ISSUE THREAD

**Issue by mxyolande** [vitoziv/VIMediaCache#4]
i want to change my local record files to cache in order to reduce network flow.
what should i do with the VICacheConfiguration

**Comment by vitoziv** [comment]
没理解错的话，你是本地录制的文件上传到服务器，但是自己预览的时候希望不要再从服务器下载是吗？

如果是这样，你可以判断哪些文件是本地存在的，在播放的时候直接取本地地址。

VIMediaCache 暂时没有支持把本地文件移动到缓存目录下面的方式。

**Comment by vitoziv** [comment]
Plan to implement this feature
