### ISSUE TITLE
某些视频偶尔不能正常播放，卡在固定的位置

### ISSUE THREAD

**Issue by passol1988** [vitoziv/VIMediaCache#41]
我在播放一个视频，要么能正常播放，要么会卡住，仔细看了下代码，发现总是卡住一个固定位置
<AVAssetResourceLoadingDataRequest: 0x1c0005860, requested offset = 933888, requested length = 15259, requests all data to end of resource = YES, current offset = 933888>
如某个视频，一直卡在933888这里，不知道是不是视频编码的原因

**Comment by vitoziv** [comment]
有 url 地址吗？ 是用最新的 commit 试的么？

**Comment by passol1988** [comment]
@vitoziv http://t1.aixinxi.net/o_1c1brn8sj1qr697h1k0q1aeqgh2a.mp4 可以用这个地址试试。

**Comment by passol1988** [comment]
@vitoziv 不知道有看到么

**Comment by vitoziv** [comment]
我这边复现不出来，用最新的 commit 1685ef7 再试试？

我切回老的代码，偶尔会遇到播放没画面的问题。

**Comment by passol1988** [comment]
用4G或者差一点的网络呢？用charles抓包发现是下载完了，但是总会卡住。用最新的代码播放没画面时有出现

**Comment by KelaKing** [comment]
用 `Network Link Conditioner` 或者 `Charles` 模拟弱网反复seek主线程卡住，Demo 必现

**Comment by passol1988** [comment]
最后用[KTVHTTPCache](https://github.com/ChangbaDevs/KTVHTTPCache)解决问题
