### ISSUE TITLE
视频资源包括mp4和m3u8两种格式，如何避免m3u8走缓存

### ISSUE THREAD

**Issue by hulian120** [vitoziv/VIMediaCache#44]
作者，你好。

我们的视频资源包括mp4和m3u8两种格式，在视频切换过程中，如果出现m3u8格式，VIMediaCache依然会对视频资源进行下载，但播放器显示无法播放。

是否可以／需要在哪里添加一个判断，使得在使用VIMediaCache的时候，可以自主选择需要下载的资源类型？我尝试在以下部分代码中添加m3u8类型判断，但是没有成功。

#pragma mark - VIURLSessionDelegateObjectDelegate

- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask didReceiveResponse:(NSURLResponse *)response completionHandler:(void (^)(NSURLSessionResponseDisposition disposition))completionHandler {
    NSString *mimeType = response.MIMEType;
    // Only download video/audio data
    if ([mimeType rangeOfString:@"video/"].location == NSNotFound &&
        [mimeType rangeOfString:@"audio/"].location == NSNotFound &&
        [mimeType rangeOfString:@"application"].location == NSNotFound) {
        completionHandler(NSURLSessionResponseCancel);
    } else {

... ...

**Comment by hulian120** [comment]
原来在初始化的时候可以处理。。。     

  if ([url hasSuffix:@"m3u8"] == YES) {
            playerItem = [AVPlayerItem playerItemWithURL:url];
        } else {
            playerItem = [self.resourceLoaderManager playerItemWithURL:url];
        }

**Comment by vitoziv** [comment]
是的，外面判断会比较好。 进入 VIMediaCache 的下载逻辑后，现在是没办法切换下载方式
