### ISSUE TITLE
播放视频地址问题

### ISSUE THREAD

**Issue by jackyzonewen** [vitoziv/VIMediaCache#5]
http://nightwander.s.qupai.me/v/7f7aa378-b80e-44e8-a326-32b19614218f.mp4?token=AMIRnTPJEMn9iZslnQZp3bKNGNtBnSC10MYJDIyMDNyAyMkNGOwQmNkJGO3AjYwIDIyACNzIDMyczM4QTM
您好，这个是我这边的视频地址，用你这个好像存在问题，无法播放，好像是assetURLWithURL的问题

**Comment by vitoziv** [comment]
```
<NSHTTPURLResponse: 0x170038b60> { URL: http://nightwander.s.qupai.me/v/7f7aa378-b80e-44e8-a326-32b19614218f.mp4?token=AMIRnTPJEMn9iZslnQZp3bKNGNtBnSC10MYJDIyMDNyAyMkNGOwQmNkJGO3AjYwIDIyACNzIDMyczM4QTM } { status code: 500, headers {
    Connection = "keep-alive";
    "Content-Length" = 57;
    "Content-Type" = "application/json;charset=UTF-8";
    Date = "Sun, 09 Oct 2016 04:56:57 GMT";
} }
```

这个视频的服务器有问题，head 方式请求，服务器 500 错误

**Comment by jackyzonewen** [comment]
@vitoziv 如果我注释掉NSURL *assetURL = [VIResourceLoaderManager assetURLWithURL:url];就可以播放出来

**Comment by jackyzonewen** [comment]
浏览器是可以播放的，如果我

**Comment by vitoziv** [comment]
注释掉那行代码，就不会对视频进行缓存 @jackyzonewen

**Comment by jackyzonewen** [comment]
嗯，是的，注释掉就不会缓存，现在如何解决这个问题？谢谢

**Comment by jackyzonewen** [comment]
@vitoziv 您好，请问一下我现在如何能解决这个问题？怎么能够播放这个视频并且缓存？

**Comment by vitoziv** [comment]
根本问题是服务端问题。合理的做法是和趣拍的开发反馈一下....他们的视频服务器用 HEAD 的方式请求会挂掉。

如果要我们兼容，会比较麻烦，要改动获取视频信息的代码。现在是通过 HEAD 请求获取视频的文件长度信息，需要用其它方法获取到视频长度信息。

**Comment by vitoziv** [comment]
部分视频服务器不支持 HEAD 的问题如何兼容，需要有个方案

**Comment by jackyzonewen** [comment]
@vitoziv https://github.com/DaMingShen/SUCacheLoader这个库可以播放趣拍的视频，获取文件长度信息有什么不一样的？

**Comment by vitoziv** [comment]
优化了一下获取文件信息的逻辑，不再通过 head 的方式请求获取。 

ref: ec461936fe5d42be21ce0d36bd0e5d6e513562a6

**Comment by vitoziv** [comment]
可以试试:
pod 'VIMediaCache', :git => 'https://github.com/vitoziv/VIMediaCache.git', :commit => 'ec46193'

@jackyzonewen
