### ISSUE TITLE
url 中包含中文时会crash

### ISSUE THREAD

**Issue by DamonChen117** [vitoziv/VIMediaCache#51]
VIResourceLoaderManager

originURL = [NSURL URLWithString:queryItem.value];

改成

originURL = [NSURL URLWithString:[queryItem.value stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];

**Comment by vitoziv** [comment]
最新版本的代码应该没有这个问题了，最新代码目前还没有打到新版本的tag里，需要在 podfile 指定 commit 的方式导入

cc: https://github.com/vitoziv/VIMediaCache/blob/master/VIMediaCache/ResourceLoader/VIResourceLoaderManager.m#L51
