### ISSUE TITLE
cache 文件只取原始url的最后一个元素导致问题

### ISSUE THREAD

**Issue by DamonChen117** [vitoziv/VIMediaCache#52]
+ (NSString *)cachedFilePathForURL:(NSURL *)url {
    return [[self cacheDirectory] stringByAppendingPathComponent:[url lastPathComponent]];
}

比例两个URL
http://a.b.c/A/media.mp3
http://a.b.c/B/media.mp3
就会出现问题

**Comment by vitoziv** [comment]
https://github.com/vitoziv/VIMediaCache/blob/master/VIMediaCache/Cache/VICacheManager.m#L48

最新版本的代码已经不是这个实现了，你用的版本似乎是很老的版本

**Comment by DamonChen117** [comment]
Installing VIMediaCache (0.3)

**Comment by vitoziv** [comment]
你先用 commit 的方式指定到最新代码吧，我晚点更新一下提供 0.4 版本。 0.3 版本后有一些修复和改动

**Comment by DamonChen117** [comment]
好的 谢谢

**Comment by vitoziv** [comment]
已经可以使用 0.4 版本
