### ISSUE TITLE
一些功能上的疑问

### ISSUE THREAD

**Issue by ZeroOnet** [vitoziv/VIMediaCache#53]
1. VIMediaCache 的默认缓存文件名为 URL 的 absoluteString，但是因为 cdn 加速，可能导致同一视频文件被缓存多次，因为它们的主机不同；
2. 缓存文件是以可播放的 .mp4 直接存放于 tmp 目录下，在越狱手机上，可以直接拿到该视频文件进行播放。如果视频文件是有版权保护的话，可能有损公司的利益。再者，tmp 目录下的文件会被系统不定期清理，如果想要达到缓存了的视频能够离线播放，是不是应该将其放在 Library/Caches 这个目录下呢？在将 NSData 写入文件之前可否先进行加密了？

感谢贵公司的开源精神，VIMediaCache 帮助我完成了最近项目上视频缓存的需求，鞠躬......

**Comment by vitoziv** [comment]
你好，

1. 这个的确是个好问题。要解决这个问题，可以把缓存的文件名开放出来，可以让外部通过插件的方式自己定义缓存的文件名，这个实现上也比较简单。
2. 缓存的文件地址是可以修改的，你可以再 VICacheManager 类提供的 API 看到修改缓存目录的 API。

如果有什么更好的改进，欢迎提意见以及 pr 哈。感谢

**Comment by ZeroOnet** [comment]
关于缓存文件名，可以使用自定义的方式，也可以不自定义。
- 如果通过开放一个外部接口的话，使用者还得逐一赋值，比如为 NSURL 扩展一个 cacheKey 的属性。因为 VIMediaCache 内部还有 NSURL 的传递，这样略显麻烦。特别是在 Swift 中，你还得使用 as 将 URL 转换为 NSURL，然后才能赋值。
- 如果不自定义的话，我们就要尽可能保证相同资源不重复缓存。鉴于存放资源的服务器的文件路径（变动资源路径相对常见），或者说最终请求的文件名几乎不会被改变，它作为 cacheKey 其实已经能够唯一标识该文件了。所以我觉得使用 NSURL 的 lastPathComponent 的 MD5 作为缓存文件名就足够了。

**Comment by ZeroOnet** [comment]
关于缓存文件名，可以使用自定义的方式，也可以不自定义。
- 如果通过开放一个外部接口的话，使用者还得逐一赋值，比如为 NSURL 扩展一个 cacheKey 的属性。因为 VIMediaCache 内部还有 NSURL 的传递，这样略显麻烦。特别是在 Swift 中，你还得使用 as 将 URL 转换为 NSURL，然后才能赋值。
- 如果不自定义的话，我们就要尽可能保证相同资源不重复缓存。鉴于存放资源的服务器的文件路径（变动资源路径相对常见），或者说最终请求的文件名几乎不会被改变，它作为 cacheKey 其实已经能够唯一标识该文件了。所以我觉得使用 NSURL 的 lastPathComponent 的 MD5 作为缓存文件名就足够了。

**Comment by vitoziv** [comment]
用 lastPathComponent 的 MD5 做为缓存文件名一样会遇到问题，有些文件服务商的文件地址是可以根据用户自定义命名的，比如：http://a.b.c/1/2.mp4 和 http://a.b.c/2/2.mp4，完整路径不一样但是 lastPathComponent 却是一样的。所以外部的各种业务情况第三方库不一定能全部覆盖，需要开发者自己根据自己的业务去处理。

关于缓存文件命名，库的内部肯定是会有自己默认的实现，如果外部有自己的需要，再统一使用自己的命名规则就好。实现一次命名规则不是什么麻烦的事情对吧 😃

**Comment by ZeroOnet** [comment]
。。。。。。
确实如此，如果要满足多方的需求，提供自己的命名规则是必要的。

**Comment by vitoziv** [comment]
可以看看这个实现  9c698ae920
