### ISSUE TITLE
Could you please tell me how to restart cache music file after having removed it?

### ISSUE THREAD

**Issue by panyult** [vitoziv/VIMediaCache#6]
你好，我用fileManager移除了本地缓存好的mp3文件，重启app之后，就不能正常播放和缓存MP3
文件了。正在研究源码中。。。希望作者能告知怎么正确删除本地缓存。谢谢！

**Comment by vitoziv** [comment]
可以看这个 commit 的实现 5a91f4ab33e16b91b7c620b562a842bd31f72537

可以用 VICacheManger 的 cleanCacheForURL 或者 cleanAllCacheWithError 方法删除缓存，通过 calculateCachedSizeWithError 获取缓存文件总大小

**Comment by panyult** [comment]
太感谢了！你的回答给我很大的帮助！拜谢！刚刚研究完你的源代码，我也自己写了个删除本地缓存的方法，不过还是你的更规范些，毕竟，是你的开源库嘛。赞！你太棒啦！

**Comment by vitoziv** [comment]
@panyult  赞，以后遇到问题，有什么改进一定要来提 pr 哟
