### ISSUE TITLE
如果想缓存过歌曲下次再播放这个歌曲就不用缓存直接播放本地的.改怎么修改?

### ISSUE THREAD

**Issue by gaohengwei** [vitoziv/VIMediaCache#8]
当我缓存第二个歌曲的时候.会把第一首歌给覆盖掉.文件中始终就是只有一首歌

**Comment by vitoziv** [comment]
可以用 `[VICacheManager cachedFilePathForURL:(NSURL *)url]` 获取歌曲文件地址

**Comment by gaohengwei** [comment]
还是不行.要不你加下我QQ吧.347246732

**Comment by vitoziv** [comment]
同一个 url 只会缓存一个文件，VICacheManager 有方法可以清理缓存。

**Comment by vitoziv** [comment]
你的描述不是很清楚  :)
